apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ocf.io/nfs-provisioner
            - name: NFS_SERVER
              value: filehost.ocf.berkeley.edu
            - name: NFS_PATH
              value: /opt/homes/services/nfs-provisioner
      volumes:
        - name: nfs-client-root
          nfs:
            server: filehost.ocf.berkeley.edu
            path: /opt/homes/services/nfs-provisioner
